apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "distribution.fullname" . }}-config
  labels:
    {{- include "distribution.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- toYaml .Values.config | nindent 4 }}
